#!/bin/bash
# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2009-2018 ANSSI. All Rights Reserved.
# USB printer devices creation/removal hotplug handler for CLIP
# Copyright 2009 SGDN/DCSSI
# Copyright 2009 SGDN
# Author: Benjamin Morin <clipos@ssi.gouv.fr>
# Author: Vincent Strubel <clipos@ssi.gouv.fr>
#
# All rights reserved

source /lib/clip/printer.sub || exit 1

[[ -n ${MAJOR} ]] || exit 0
[[ -n ${MINOR} ]] || exit 0
[[ -n ${DEVPATH} ]] || exit 0

[[ ${MAJOR} == "180" ]] || exit 0


NUM="${DEVPATH##*/lp}"

case "${1}" in
	add)
		make_carddevs "${NUM}" && clip-device-notify "add" "printer"
		;;
	remove)
		remove_carddevs "${NUM}" && clip-device-notify "remove" "printer"
		;;
	*)
		logger -p daemon.warning "hotplug/printer: unknown action ${1}"
		exit 1
		;;
esac

exit 0

